menus:
    HOME: /
    # ARCHIVE: /archives/
    GITHUB: https://github.com/justclear
    # ABOUT: /about/

favicon: /favicon.png
logo: /images/logo.jpg
title: Just
description: ''
url: http://justclear.github.io/
startyear: 2015
thisyear: 2019
