menus:
    HOME: /
    IDEA: /idea
    ABOUT: /about/
    GITHUB: https://github.com/justclear

favicon: /favicon.png
logo: /images/logo.jpg
title: Just
description: ''
url: http://justclear.github.io/
startyear: 2015
thisyear: 2019
