menu:
    blog: /
    archive: /archives/
    gitHub: https://github.com/justclear
    rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png
title: Just
description: ''
url: http://justclear.github.io/
cover:
    home:
    archive:

# Comment
# e.g disqus: seansun
disqus:

# Copyright Infomation
startyear: 2015
